### ISSUE TITLE
regtest won't upgrade past sapling

### ISSUE THREAD

**Issue by buck54321** [ZclassicCommunity/zclassic#83]
For example, clear your regtest data directory and run 

`zclassicd --regtest -nuparams=5ba81b19:1 -nuparams=76b809bb:2 -nuparams=821a451c:3 -nuparams=930b540d:4`

and then generate blocks

```
zclassic-cli generate 1
zclassic-cli generate 1
zclassic-cli generate 1
```

the node will hang while mining the third block and will not recover. Cannot shut down.

**Comment by RhettCreighton** [comment]
I believe this can be fixed by explicitly setting the equihash parameters in the command-line like this:
`./zclassicd --regtest -nuparams=5ba81b19:1 -nuparams=76b809bb:2 -nuparams=821a451c:3 -nuparams=930b540d:4  -eqparams=5ba81b19:48:5 -eqparams=76b809bb:48:5 -eqparams=821a451c:48:5 -eqparams=930b540d:48:5` 

for regnet, the params are 48:5

On mainnet, the equihash parameters were changed to 192:7  The reason for changing equihash parameters was so they would not be compatible with other miners on NiceHash at the time that could easily switch hashrate to 51% attack the chain

Does passing the extra commandline param work for your case?

**Comment by buck54321** [comment]
That works. Thank you.
